# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1d3807201f8f9fc0458a6d21a874e666d075b7a7bba12916e5a1717b0cecbe42e4d1cdc3cff813b02e228297d157e0b3ffd6e0d893063ad94a14ff5a6ca0f2b

test:
  secret_key_base: f24c679c4438be977cec7d976ea7b86e69fac45756be40cf826157c31115372cdaf40322590210efb05af9839a47cde9a1d96d67c5d73f2148a5d86ee63b23cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
